#!/bin/sh

##
# Updates the gem caches for all the supported ruby interpreters.  Run
# it after each change to the Gemfile.
#
# Hopefully this will not be necessary after bundler 0.10 comes out.

RVM_VERSIONS="ree-1.8.7-2009.10,jruby-1.4.0"

# 1.8.7 doesn't match the CI version because the CI version doesn't work on OS X 10.5
rvm $RVM_VERSIONS gem bundle
rvm $RVM_VERSIONS gem bundle --prune-cache
