#!/bin/sh

##
# Updates the gem caches for all the supported ruby interpreters.  Run
# it after each change to the Gemfile.
#
# Hopefully this will not be necessary after bundler 0.10 comes out.

RVM_VERSIONS="ree-1.8.7-2010.02,ruby-1.9.1-p378,jruby-1.4.0"

rvm $RVM_VERSIONS gem bundle
rvm $RVM_VERSIONS gem bundle --prune-cache
