desc 'Launch everything for the CAS example'
task :launch do
  processes = []

  Dir.chdir('..') do
    processes << fork { sh "bundle exec rackup cas/rubycas_server.ru" }
    processes << fork { sh "bundle exec rackup cas/fortune_server.ru" }
    processes << fork { ruby "-rubygems cas/cas_proxy_callback.rb" }
    processes << fork { ruby "-rubygems cas/fortune_client.rb" }
  end

  trap('INT') { Process.kill('TERM', *processes) }

  Process.waitall
end

desc 'Reset CAS server state'
task :clean do
  rm_rf Dir['var/*']
end

task :default => :launch
