require File.join(File.dirname(__FILE__), %w(.. test))

##
# Contains helpers for writing tests on bcsec-protected code.
module Bcsec::Test::Helpers
  ##
  # Generates an environment hash that marks `user` as logged in.  You can use
  # the generated hash in pre-existing requests, merge the hash with the
  # environment generated by `Rack::MockRequest.env_for`, etc.
  #
  # @param [String,Bcsec::User] user
  #   a user's username or a {Bcsec::User} object.  Your Bcsec configuration
  #   must use an authority that implements `find_user` for username lookup to
  #   work.
  # @return [Hash<String, Bcsec::Rack::Facade>] a Hash of the form
  #   `{'bcsec' => (a Bcsec::Rack::Facade)}`
  def login_env(user)
    u = Bcsec::User === user ? user : Bcsec.authority.find_user(user)

    { 'bcsec' => Bcsec::Rack::Facade.new(Bcsec.configuration, u) }
  end
end
