require File.join(File.dirname(__FILE__), %w(.. test))

##
# Contains helpers for writing tests on aker-protected code.
module Aker::Test::Helpers
  ##
  # Generates an environment hash that marks `user` as logged in.  You can use
  # the generated hash in pre-existing requests, merge the hash with the
  # environment generated by `Rack::MockRequest.env_for`, etc.
  #
  # @param [String,Aker::User] user
  #   a user's username or a {Aker::User} object.  Your Aker configuration
  #   must use an authority that implements `find_user` for username lookup to
  #   work.
  # @return [Hash<String, Aker::Rack::Facade>] a Hash of the form
  #   `{'aker' => (a Aker::Rack::Facade)}`
  def login_env(user)
    u = Aker::User === user ? user : Aker.authority.find_user(user)

    { 'aker' => Aker::Rack::Facade.new(Aker.configuration, u) }
  end
end
